alias   j=jobs
alias   vi=vim
alias   more=less

alias   ll="ls -alF"

alias   rm="rm -i"
alias   cp="cp -i"
alias   mv="mv -i"

alias   s="screen"
alias   scd="screen -d"
alias   scr="screen -r"
alias   sls="screen -ls"
alias   scw="screen -w"

alias	g=git
alias	gst="git status"
alias	gbr="git branch"
alias	gco="git checkout"
alias   gs="git stash"
alias   gsl="git stash list"
alias   gfrbm="git fetch && git rebase origin/master"
alias   gdm="git diff master"
alias   gl1="git log -1"

alias   trr="traceroute"

export EDITOR=vim
export PAGER=less

