alias   d='LC_ALL=C date "+%c"'
alias   f="fping -l"
alias	g=git
alias   j=jobs
alias   m='mount'
alias   p="ping"
alias   s="screen"
alias   t="telnet"
alias   u="uptime"


alias   rm="rm -i"
alias   cp="cp -i"
alias   mv="mv -i"

alias   ap="arping"
alias   ff='find . -type f'
alias   ll="ls -alF"
alias   vi=vim
alias   td="sudo tcpdump -nnn"

alias	alu="apt list --upgradable"
alias   ali="apt list --installed"
alias	aup="apt update"
alias	aug="apt upgrade"

alias   scd="screen -d"
alias   scr="screen -r"
alias   scl="screen -ls"
alias   scw="screen -w"

alias   trr="traceroute -n"

alias	gst="git status"
alias	gbr="git branch"
alias	grb="git rebase"
alias	gco="git checkout"
alias	gcom="git checkout master"
alias   gs="git stash"
alias   gsl="git stash list"
alias   gfrbm="git fetch && git rebase origin/master"
alias   gdm="git diff master"
alias   gl1="git log -1"

alias   more=less

alias	sshp="ssh -o PasswordAuthentication=yes -o PubkeyAuthentication=no"
alias	sshk="ssh -o PasswordAuthentication=no -o PubkeyAuthentication=yes"

alias timestamp="date '+%Y%m%d%H%M'"

export EDITOR=vim
export PAGER=less

